# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-14 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180213_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='reply',
        ),
    ]
