# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='profile_photos')),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('hamlet_name', models.CharField(blank=True, default='', max_length=100)),
                ('ward_name', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('occupation', models.CharField(blank=True, default='', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=100)),
                ('educational_qualification', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
