# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171211_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hamlet_name',
            new_name='village',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ward_name',
            new_name='ward',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'm'), ('female', 'f')], default='m', max_length=100),
        ),
    ]
