# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-20 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180208_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diasbilities',
            field=models.CharField(blank=True, choices=[('n', 'none'), ('s', 'specify')], max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='employement_status',
            field=models.CharField(blank=True, choices=[('e', 'employed'), ('u', 'unemployed')], max_length=100),
        ),
    ]
